# -*- mode: ruby -*-
# vi: set ft=ruby :
# This is a Vagrant file for testing the recipe
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = 'hello-service'
  config.vm.box = 'chef/centos-6.5'
  config.omnibus.chef_version = 'latest'
  config.berkshelf.enabled = true
  config.vm.network :forwarded_port, guest: 80, host: 8000

  config.vm.provision :chef_solo do |chef|
    # Configure the boxes environment.  We use this to generate the env_url
    chef.environments_path = "environments"
    chef.roles_path = "roles"

    chef.environment = "stage"

    # override some of the role values with the S3 config
    chef.json = {
      #"slug-deployment" => {
      #  "slug_url" => "s3://#{ENV['S3_BUCKET']}/hello-service/hello-service-latest.tgz",
      #  "env_url" => "s3://#{ENV['S3_BUCKET']}/hello-service/environments/<% node.chef_environment %>.env",
      #},
      "s3cmd" => {
        "access_key" => ENV['AWS_ACCESS_KEY_ID'],
        "secret_key" => ENV['AWS_SECRET_ACCESS_KEY']
      }
    }
    chef.run_list = ["role[hello-service]"]
  end
end
